#!/usr/bin/env python3
from __future__ import annotations
"""
generate_sync_commands.py  —  Generate the consolidation rsync script

Reads reconcile_dirs.tsv (produced by smugmug_reconcile_dirs.py) and
generates sync_commands.sh — an interactive shell script that merges
the SmugMug download into your local library.

rsync flags used
────────────────
  --checksum   Compare files by content hash, not modification time.
               Files with identical bytes are SKIPPED, preserving the
               local file's original modification date.
               Files whose EXIF was improved (captions, GPS, timestamps
               added by the download script) have different bytes and ARE
               overwritten with the better version.

  (no --delete)  Local-only files — camera photos never uploaded to
               SmugMug, manual additions, etc. — are always preserved.
               Deduplication can be done separately later.

After syncing, restore photo dates from EXIF with:
  exiftool -r -q '-FileModifyDate<DateTimeOriginal' /your/library

Usage:
  python3 generate_sync_commands.py \\
    --tsv reconcile_dirs.tsv \\
    --local /Volumes/photo \\
    --downloaded "/path/to/smugmug/download"
"""

import argparse
import csv
import sys
from pathlib import Path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--tsv",        default="reconcile_dirs.tsv")
    parser.add_argument("--local",      required=True,
                        help="Root of local photo library (e.g. /Volumes/photo)")
    parser.add_argument("--downloaded", required=True,
                        help="Root of SmugMug download directory")
    args = parser.parse_args()

    tsv_path = Path(args.tsv)
    if not tsv_path.exists():
        sys.exit(f"TSV not found: {tsv_path}  (run smugmug_reconcile_dirs.py first)")

    lo_root = Path(args.local)

    with open(tsv_path, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f, delimiter="\t"))

    by_action: dict[str, list] = {"REPLACE":[],"MERGE":[],"ADD":[],"REVIEW":[]}
    for row in rows:
        by_action.setdefault(row["Action"], []).append(row)

    replace_rows = by_action["REPLACE"]
    merge_rows   = by_action["MERGE"]
    add_rows     = by_action["ADD"]
    review_rows  = by_action["REVIEW"]
    active_rows  = replace_rows + merge_rows + add_rows

    lines = [
        "#!/usr/bin/env bash",
        "# sync_commands.sh — generated by generate_sync_commands.py",
        "#",
        "# rsync --checksum: identical files are SKIPPED (local mtime preserved).",
        "# No --delete anywhere: local-only files are always kept.",
        "#",
        f"# Total operations: {len(active_rows)}",
        f"#   REPLACE: {len(replace_rows)}  MERGE: {len(merge_rows)}  "
        f"ADD: {len(add_rows)}  REVIEW (skipped): {len(review_rows)}",
        "#",
        "# After completion, run:",
        f"#   exiftool -r -q '-FileModifyDate<DateTimeOriginal' '{lo_root}'",
        "",
        "set -euo pipefail",
        "DONE=0",
        "FAIL=0",
        "",
    ]

    def rsync_block(action: str, dl_path: str, lo_path: str,
                    dl_name: str, lo_name: str,
                    dl_files: str, lo_files: str,
                    lo_only: str, overlap: str) -> list[str]:
        return [
            f'echo "  {action}: {dl_name}  →  {lo_name}'
            f'  ({dl_files} dl / {lo_files} local / {lo_only} local-only)"',
            f'if rsync -a --checksum \\',
            f'     "{dl_path}/" \\',
            f'     "{lo_path}/"; then',
            f'  DONE=$((DONE+1))',
            f'else',
            f'  echo "  ✗ rsync failed for {dl_name}"',
            f'  FAIL=$((FAIL+1))',
            f'fi',
            '',
        ]

    # ── REPLACE ───────────────────────────────────────────────
    if replace_rows:
        lines += [f'echo "━━━ REPLACE ({len(replace_rows)}) ━━━"', ""]
        for row in replace_rows:
            lines += rsync_block(
                "REPLACE",
                row.get("Downloaded_Path",""), row.get("Local_Path",""),
                row.get("Downloaded_Folder","?"), row.get("Local_Folder","?"),
                row.get("DL_Files","?"), row.get("Local_Files","?"),
                row.get("Local_only (rescue these!)","0") or "0",
                row.get("FileOverlap%","?"),
            )

    # ── MERGE ─────────────────────────────────────────────────
    if merge_rows:
        lines += [f'echo "━━━ MERGE ({len(merge_rows)}) ━━━"', ""]
        for row in merge_rows:
            lines += rsync_block(
                "MERGE",
                row.get("Downloaded_Path",""), row.get("Local_Path",""),
                row.get("Downloaded_Folder","?"), row.get("Local_Folder","?"),
                row.get("DL_Files","?"), row.get("Local_Files","?"),
                row.get("Local_only (rescue these!)","0") or "0",
                row.get("FileOverlap%","?"),
            )

    # ── ADD ───────────────────────────────────────────────────
    if add_rows:
        lines += [f'echo "━━━ ADD ({len(add_rows)}) ━━━"', ""]
        for row in add_rows:
            dl_name = row.get("Downloaded_Folder","?")
            dl_path = row.get("Downloaded_Path","")
            target  = str(lo_root / dl_name)
            lines += [
                f'echo "  ADD: {dl_name}  ({row.get("DL_Files","?")} files)"',
                f'mkdir -p "{target}"',
                f'if rsync -a --checksum \\',
                f'     "{dl_path}/" \\',
                f'     "{target}/"; then',
                f'  DONE=$((DONE+1))',
                f'else',
                f'  echo "  ✗ rsync failed for {dl_name}"',
                f'  FAIL=$((FAIL+1))',
                f'fi',
                '',
            ]

    # ── REVIEW ────────────────────────────────────────────────
    if review_rows:
        lines += [f'echo "━━━ REVIEW ({len(review_rows)} skipped — inspect manually) ━━━"']
        for row in review_rows:
            dl  = row["Downloaded_Folder"]
            loc = row.get("Local_Folder","(no match)")
            ovr = row.get("FileOverlap%","?")
            lines.append(f'echo "  REVIEW: {dl}  ↔  {loc}  overlap={ovr}%"')
        lines.append('')

    lines += [
        'echo ""',
        f'echo "━━━ DONE: $DONE synced, $FAIL failed ━━━"',
        'echo ""',
        'echo "Restore file modification dates from EXIF:"',
        f'echo "  exiftool -r -q \'-FileModifyDate<DateTimeOriginal\' \'{lo_root}\'"',
    ]

    # ── Write script ──────────────────────────────────────────
    out_path = Path("sync_commands.sh")
    out_path.write_text("\n".join(lines), encoding="utf-8")
    out_path.chmod(0o755)

    # ── Summary table ─────────────────────────────────────────
    print(f"\n{'═'*65}")
    print(f"  SYNC PLAN  —  {len(active_rows)} operations")
    print(f"{'═'*65}")
    print(f"  {'Action':<10} {'Downloaded album':<40} {'Local album':<40}")
    print(f"  {'─'*10} {'─'*40} {'─'*40}")
    for row in replace_rows + merge_rows + add_rows:
        action  = row["Action"]
        dl_name = row.get("Downloaded_Folder","?")[:39]
        lo_name = row.get("Local_Folder","(new)")[:39]
        lo_only = int(row.get("Local_only (rescue these!)","0") or 0)
        note    = f"  [{lo_only} local-only]" if lo_only > 0 else ""
        print(f"  {action:<10} {dl_name:<40} {lo_name:<40}{note}")
    if review_rows:
        print(f"\n  {len(review_rows)} REVIEW cases not included — see reconcile_dirs.tsv")
    print(f"{'═'*65}\n")
    print(f"✅ Generated sync_commands.sh")
    print(f"   Review the plan above, then run:")
    print(f"   bash sync_commands.sh")
    print(f"\n   --checksum: identical files skipped (local mtime preserved)")
    print(f"   No --delete: local-only files always kept")

    ans = input(f"\nRun sync_commands.sh now? [y/N] ")
    if ans.lower() == "y":
        import subprocess
        subprocess.run(["bash", "sync_commands.sh"])


if __name__ == "__main__":
    main()
